version: '3'
services:

  # Nginx client server
  myclients-nginx-client:
    container_name: myclients-nginx-client
    build:
        context: .                  # (!) Dockerfile doesn't see anything outside of this context
        dockerfile: ./docker/nginx-client/Dockerfile
    restart: always
    stdin_open: true                # Needed for HMR
    environment:
      - CHOKIDAR_USEPOLLING=true    # Needed for HMR
    ports:
      - 47344:3000
    volumes:
      - ./client:/var/www
      - /var/www/node_modules       # We need this volume so that it won't be overwritten by our bind mount. Since node_modules on the host is empty, the bind will map an empty directory to the container, overriding the new node_modules directory and preventing our application from starting. The named node_modules volume solves this problem by persisting the contents of the node_modules directory and mounting it to the container, hiding the bind.
    networks:
      - app-network


  # MySQL server for the server side app
  myclients-mysql-server:
    image: mysql:8.0
    container_name: myclients-mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "16370:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: m1c*liE_ntS-p@awz88**z
      MYSQL_DATABASE: myclients
    networks:
      - app-network


  # Nginx server for the server side app
  myclients-nginx-server:
    container_name: myclients-nginx-server
    image: nginx:1.17-alpine
    restart: always
    ports:
      - 41166:80
    volumes:
      - ./server:/var/www
      - ./docker/nginx-server/etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - myclients-php-server
    - myclients-mysql-server
    - myclients-redis-server
    networks:
      - app-network


  # PHP server for the server side app
  myclients-php-server:
    build:
      context: .        # (!) Dockerfile doesn't see anything outside of this context
      dockerfile: ./docker/php-server/Dockerfile
    container_name: myclients-php-server
    restart: always
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./server:/var/www
      - ./docker/php-server/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /var/www/vendor       # We need this volume so that it won't be overwritten by our bind mount. Since vendor on the host is empty, the bind will map an empty directory to the container, overriding the new vendor directory and preventing our application from starting. The named vendor volume solves this problem by persisting the contents of the vendor directory and mounting it to the container, hiding the bind.
    networks:
      - app-network
    depends_on:
      - myclients-mysql-server
      - myclients-redis-server


  # Redis server for the server side app
  myclients-redis-server:
    image: redis:6.0
    container_name: myclients-redis-server
    restart: always
    ports:
        - 16468:6379
    networks:
      - app-network


# Networks
networks:
  app-network:
    driver: bridge